### ISSUE TITLE
README.md misformat

### ISSUE THREAD

**Issue by gelsrc** [zelloptt/zellowork-windows-client-sdk#1]
There is README.md misformat now. A number of errors are in subtitle sentences (marked with ##, ###). At least one space is required between the # characters and the heading’s contents.

For example, the following line:
```
###Step ...
```
must be written as:
```
### Step  ...
```

Reference to the spec is [Example 34](https://github.github.com/gfm/#example-34) and a paragraph before.

See also the attached image for explanation.

![misformat](https://cloud.githubusercontent.com/assets/22377517/24090410/b3d97fa0-0d61-11e7-9b28-b6dd3e7375fe.png)

**Comment by agatx** [comment]
Fixed in 6c82ccbfbd3a30d6c26cbccdecae339a2365556c
